!define _Master << (M, Gold) >>
!define _Transaction << (T, DarkSeaGreen) >>
skinparam LineType ortho

legend top left
    凡例
    |= 説明 |= 記号 |
    | 0 or 1 | <transparent> --o\| |
    | 1のみ  | <transparent> --\|\| |
    | 0以上  | <transparent> --o{ |
    | 1以上  | <transparent> --\|{ |
    ----
    M = Master
    T = Transaction
    ----
    ● = 必須項目
end legend
